# Dependencies
markdown:            redcarpet
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:               SAMIT
tagline:             'Small Animal Molecular Imaging Toolbox'
description:         'The aim of this toolbox is to facilitate the construction of new tracer specific templates and the subsequent voxel-based analysis of small animal PET and SPECT brain images.'
url:                 http://http://mic-umcg.github.io
baseurl:             "/samit"
paginate:            5

# About/contact
author:
  name:              David Vállez
  email:             samit@umcg.nl

# Custom vars
version:             v1.2
zenodo:              https://zenodo.org/record/14785

# Exclude these files from _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
